spring.application.name=Auth

spring.datasource.url=jdbc:postgresql://localhost:5433/authdb
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=INFO

spring.docker.compose.enabled=false

springdoc.swagger-ui.path=/swagger

#### EMAIL ####

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

VERIFICATION_CODE_EXPIRATION=${VERIFICATION_CODE_EXPIRATION}
auth.refresh-token.cleanup-cron=0 0 3 * * *

##### LOGS #####

logging.level.com.api.auth=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId:-N/A}] %logger{36} - %msg%n

##### RATE LIMIT #####
auth.rate-limit.enabled=true
auth.rate-limit.trust-forwarded-headers=true
auth.rate-limit.trusted-proxies=127.0.0.1,::1
auth.rate-limit.login.max-attempts=10
auth.rate-limit.login.window-seconds=60
auth.rate-limit.verify-code.max-attempts=6
auth.rate-limit.verify-code.window-seconds=600
auth.rate-limit.forgot-password-request.max-attempts=5
auth.rate-limit.forgot-password-request.window-seconds=900
auth.rate-limit.forgot-password-verify.max-attempts=8
auth.rate-limit.forgot-password-verify.window-seconds=600
auth.rate-limit.refresh.max-attempts=30
auth.rate-limit.refresh.window-seconds=60
auth.rate-limit.redis.enabled=true
auth.rate-limit.redis.fail-open=true
auth.rate-limit.redis.key-prefix=auth:ratelimit

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false

auth.otp.max-attempts=5

auth.geolocation.connect-timeout-ms=700
auth.geolocation.read-timeout-ms=1000
auth.geolocation.retry.max-attempts=2
auth.geolocation.retry.backoff-ms=150

auth.risk.new-device-score=40
auth.risk.new-location-score=35
auth.risk.unusual-ip-score=25
auth.risk.suspicious-threshold=40
auth.risk.step-up-threshold=60

#login: 10 req / 60s
#verify-code: 6 req / 600s
#forgot-password request: 5 req / 900s
#forgot-password verify: 8 req / 600s
#refresh: 30 req / 60s