spring.application.name=Auth

spring.datasource.url=jdbc:postgresql://localhost:5433/authdb
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

spring.docker.compose.enabled=false

springdoc.swagger-ui.path=/swagger

# JWT Configuration
#jwt.secret=minhaChaveSuperSecretaDeAutenticacaoJWT1234!